CREATE TABLE IF NOT EXISTS PUNTO_DE_VENTA (
    PUNTO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PUNTO_NAME VARCHAR(100),
    PUNTO_DELETED_DATE DATE
);


CREATE TABLE IF NOT EXISTS COSTO_ENTRE_PUNTOS (
    COST_A_PUNTO_ID BIGINT,
    COST_B_PUNTO_ID BIGINT,
    COST_AMOUNT int,
	PRIMARY KEY (COST_A_PUNTO_ID,COST_B_PUNTO_ID)
);