version: '3.8'
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # MySQL configuration
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ventasDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ventasDB
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge